### PR TITLE
Patch Regex DDoS

### PR DESCRIPTION
**Pull request by mctaggaj**
mime versions <1.4.1 have a security vulnerability. (https://github.com/broofa/node-mime/releases/tag/v1.4.1)

### CODE REVIEW

**Comment by mctaggaj** [comment]
The npm audit tool has revealed a potential DDoS vulnerability.
image

Is opening a PR against this repo the best way to get the issue resolved?

**Comment by mctaggaj** [comment]
@andrewrk Is this the right process to get this updated?

**Comment by RabeaWahab** [comment]
@andrewrk can we merge this change?

**Comment by andrewrk** [comment]
I have no intention of spending time on this project for the foreseeable future. Fork it!

**Comment by matrus2** [comment]
You can use this fork https://www.npmjs.com/package/s3-client

**Comment by matrus2** [comment]
@andrewrk Why don't you archive this repo?

**Pull request closed without merging**
