### PR TITLE
Fixes #61: Make SyncDir count fileUploadEnd events before ending

### LINKED ISSUE #61: uploadDir uploader emits `end`-event too early
I just ran into this issue. When uploading a single image file or a file with no content the uploadDir uploader emits the `end`-event before all uploads are finished.

I wrapped the uploadDir method into a promise and the promise now resolves before all uploads are done. Any ideas why this is happening?

### PR DESCRIPTION
**Pull request by cperryk**
Fixes #61: Currently, syncDir emits "end" when the amount of data uploaded reaches the total expected amount. This can lead to "end" emitting before each file uploader emits its own "end" event. This fix makes syncDir check that all file uploaders have emitted a "fileUploadEnd" event before syncDir emits an "end" event. I've kept the original data-size criterion in there as well, but it may be redundant now.

### CODE REVIEW

**Comment by faceleg** [comment]
Looks great, would you please be able to add a test?

**Comment by cperryk** [comment]
I just ran the mocha test but "multipart upload" and "s3 download file with multipart etag" are failing for me on the latest version, 4.4.0, i.e. _without_ the changes in this pull request. Seems like an unrelated issue.

```
  1) s3 multipart upload:
     Error: timeout of 40000ms exceeded. Ensure the done() callback is being called in this test.


  2) s3 download file with multipart etag:
     Error: http status code 404
      at Request.<anonymous> (lib/index.js:463:21)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:422:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
      at TLSSocket.socketOnData (_http_client.js:312:20)
      at readableAddChunk (_stream_readable.js:147:16)
      at TLSSocket.Readable.push (_stream_readable.js:111:10)
      at TLSWrap.onread (net.js:524:20)
```

**Comment by faceleg** [comment]
I have no idea - do you want to do a push to a feature branch so I can run your updated code on my machine?

**Comment by pennycoder** [comment]
We just hit this today too with a 6byte file upload to a bucket that already has files under the specified prefix.  Glad to see someone else has hit this too with the same root cause and very similar fix.  Any chance this might go through soon?

**Comment by faceleg** [comment]
@pennycoder there are issues with the tests - do they all run (for this PR) on your machine? If I can get a verification of tests then I'll merge

**Comment by cperryk** [comment]
Put this in a feature branch — `git clone -b feat/uploader https://github.com/cperryk/node-s3-client.git`

**Comment by pennycoder** [comment]
In the current branch and the PR branch I am also seeing these two tests fail.  I will dig around a little this afternoon and attempt to root cause.  It does look to me that these two tests have issues independent of the changes.

```

  MultipartETag
    ✓ returns unmodified digest 

  s3
    ✓ get public URL 
    ✓ uploads (368ms)
    ✓ downloads (236ms)
    ✓ downloadBuffer (261ms)
    ✓ downloadStream (235ms)
    ✓ lists objects (252ms)
    ✓ copies an object (184ms)
    ✓ moves an object (389ms)
    ✓ deletes an object (197ms)
    ✓ uploads a folder (311ms)
    ✓ downloads a folder (358ms)
    ✓ uploadDir with deleteRemoved (506ms)
    ✓ lists objects (121ms)
    ✓ downloadDir with deleteRemoved (225ms)
    ✓ upload folder with delete removed handles updates correctly (1022ms)
    1) multipart upload
    2) download file with multipart etag
    ✓ deletes a folder (523ms)


  17 passing (48s)
  2 failing

  1) s3 multipart upload:
     Error: timeout of 40000ms exceeded
      at null.<anonymous> (/Users/testuser/opengit/s3b/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:119:15)

  2) s3 download file with multipart etag:
     Error: http status code 404
      at Request.<anonymous> (/Users/testuser/opengit/s3b/lib/index.js:461:21)
      at Request.callListeners (/Users/testuser/opengit/s3b/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
      at Request.emit (/Users/testuser/opengit/s3b/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (/Users/testuser/opengit/s3b/node_modules/aws-sdk/lib/request.js:596:14)
      at IncomingMessage.onHeaders (/Users/testuser/opengit/s3b/node_modules/aws-sdk/lib/event_listeners.js:189:24)
      at IncomingMessage.emit (events.js:110:17)
      at ClientRequest.<anonymous> (/Users/testuser/opengit/s3b/node_modules/aws-sdk/lib/http/node.js:47:16)
      at ClientRequest.g (events.js:199:16)
      at ClientRequest.emit (events.js:107:17)
      at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
      at TLSSocket.socketOnData (_http_client.js:317:20)
      at TLSSocket.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at TLSSocket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)

```

**Comment by faceleg** [comment]
Do you happen to have experience with http://s3ninja.net or any other s3 mocking library? I'd **love** to get some CI action happening for this repository.

**Comment by faceleg** [comment]
Also this: https://github.com/jubos/fake-s3

In an ideal world we could:

```bash
git clone node-s3-client
cd node-s3-client
npm run test
```

And have any deps and mocks installed & started with tests run against them. Doing this would remove a big barrier for community members wanting to submit PR's, and give us users a lot more confidence in the library.

**Comment by pennycoder** [comment]
We just use Jasmine (which looks very similar to Mocha) for our test harness and use it's spy mechanism to mock underlying APIs.  It would be awesome if one of these frameworks did remove the tight dependency on an s3 bucket.

That said, it seems like you would want a minimal set of end2end integration tests as a sanity check.

**Comment by faceleg** [comment]
Totally agree but I doubt we'll find a person willing to attach a credit card to an aws account, which is what we need at the moment if we wanted say, travis hooked up :(

**Comment by pennycoder** [comment]
The code in question leverages node streams.  I wonder if the delta between the tests working (or not) might be due to node version.  We are on a slightly old version - v0.12.7

**Comment by cperryk** [comment]
I'm running 5.2.0, so that could be it.

**Comment by pennycoder** [comment]
In the latest branch reverting this change https://github.com/andrewrk/node-s3-client/commit/4acd75c59b9e1ff7d79dbb471f8117010772ed8e back to the previous AWS SDK
```
    "aws-sdk": "2.0.31",
```
allows all the tests to work/pass.

**Comment by pennycoder** [comment]
First release where upload is broken is AWS release 2.1.1
http://aws.amazon.com/releasenotes/JavaScript/9016743283037269

Looks like there is something about Expect headers being needed for payloads larger than 1MB - will continue to dig.

**Comment by faceleg** [comment]
Thanks @pennycoder for your perseverance with this

**Comment by faceleg** [comment]
In other news, I think that with this https://github.com/jamhall/s3rver (or the ruby one mentioned above) combined with https://docs.travis-ci.com/user/hosts/ will allow us to get some tests going on Travis.

**Comment by pennycoder** [comment]
that sounds great!

It does *appear* to be the Expect header addition - at least when this code is removed:
```
    if (AWS.util.isNode() && len >= 1024 * 1024) {
      req.httpRequest.headers['Expect'] = '100-continue';
    }
```
upload completes successfully.  The Expect header is pretty detailed
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
With the way the current the behavior looks I wonder if the Expect+100 handshake is failing causing the client to hang.

**Comment by faceleg** [comment]
Are there serious implications of removing those 3 lines?

**Comment by pennycoder** [comment]
Unfortunately these lines are in the AWS SDK, they were part of the large object reliability fix in 2.1.1 :/

Still digging through the code.  I can see the correct response come back from the server in the AWS code.  Upon receipt the AWS client attempts to read from the stream but there isn't any data as the stream is at the end.  Eventually the socket times out.

If I remove the Etag code and just leave the instream directly in the s3Params.body then the upload completes.  The introduction of the Expect header does introduce a delay before the stream is read.  Still ramping up on Node so I need to better understand how the MultiPart Etag stuff is supposed to work.  Will be looking at this tomorrow.

**Comment by pennycoder** [comment]
Turned out that this is just a "simple" stream integration bug.  Since we are calling inStream.pipe(multipartETag) this puts the stream into flow-mode where data will being flowing on the next tick.  With files larger than 1MB AWS waits for an Expect response from the server before calling .pipe on the body stream.  With the added latency most (if not all) the data is already read from the inStream pipe by the time AWS gets around to reading from it.

The cleanest fix would seem to be changing the MultipartETag class to be a pass-through stream (it is already 99.9% like this) and then setting this stream in the s3Params.body property.  Another fix would be to call .pause() on the inStream but that relies on implicit .pipe() behavior turning the stream back into flow-mode and on AWS implementation details (that they are currently calling .pipe()).  

I will put a PR under @cperryk 's branch and both could be taken together.

**Comment by pennycoder** [comment]
Little bit different in public GIT - here is a PR for the changes to fix the tests:
https://github.com/andrewrk/node-s3-client/pull/118

**Comment by cperryk** [comment]
The feat/uploader branch on this now passes all tests. `git clone -b feat/uploader https://github.com/cperryk/node-s3-client.git`

**Comment by dvalentiate** [comment]
oh dear, well I was foolish and duplicated this work and came up with a very similar solution. But I also have tests!

I didn't mock S3 though and the to previously broken tests remain so on my pull request.

I guess I prefer mine because it has the tests.

https://github.com/andrewrk/node-s3-client/pull/130

Let me know what you guys think.

**Comment by faceleg** [comment]
I acted too hastily merging #130, reverted.

@cperryk what is your opinion regarding which should be merged?

**Comment by cperryk** [comment]
Go with #130. It adds the check for downloads as well as uploads, whereas my PR only applies to uploads.

**Comment by faceleg** [comment]
OK, apologies again, should have discussed which to merge first.

**Comment by faceleg** [comment]
Closing in favour of #130

**Pull request closed without merging**
