### PR TITLE
Update graceful-fs!

### PR DESCRIPTION
**Pull request by rsflow**
Node 6 gives an error with graceful-fs 3.

### CODE REVIEW

**Comment by grimabe** [comment]
+1 for merge

**Comment by Blechhirn** [comment]
@faceleg Can we push a new version to npm? Seems worth it.

**Comment by jrbenito** [comment]
More than a year since last version up, need to bump version.

**Comment by franciscop** [comment]
> npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

**Comment by rsflow** [comment]
@franciscop

**Comment by colm-mcqs** [comment]
Good man, @aiflow . Be great to get this merged. :+1:

**Pull request merged**
